name: aws_lambda_core
description: This package is responsible to provide the basic resources to Lambda Functions with Clean Dart
version: 1.0.0-dev.2
repository: https://github.com/davidsdearaujo/aws_lambda_core

environment:
  sdk: '>=2.14.0-377.7.beta <3.0.0'


dependencies:
  aws_lambda_dart_runtime: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
